### ISSUE TITLE
Exercício 1 - Planilha básica google sheets 

### ISSUE THREAD

**Issue by ebertti** [ebertti/Javascript202#1]
Criar um script no menu do google sheets para preencher campos da planilha baseado em celulas das colunas anterios.

Ex:

![image](https://user-images.githubusercontent.com/140394/80247072-db654780-8643-11ea-8455-0baab834122f.png)

Postar suas respostas como comentários nesta issue.

Usem formatação de código como:

![image](https://user-images.githubusercontent.com/140394/80247290-2da66880-8644-11ea-9a0c-fd9d900d1775.png)

**Comment by fjuncal** [comment]
(não consegui pegar os 2 valores(nome e sobrenome) e concatenar, não achei o método correto)
'''javascript

function gerarSenha(){
  var spreadsheet = SpreadsheetApp.getActive()
  let range = spreadsheet.getRange('D2:D')
  
  let aleatorio = Math.random().toString(36).substr(2, 5);
  
  spreadsheet.getCurrentCell().setValue(aleatorio)

}

function gerarEmail(){
  var spreadsheet = SpreadsheetApp.getActive()
  let range = spreadsheet.getRange('C2:C')
  
  
  let nome = spreadsheet.getRange('A2:A')
  let sobrenome = spreadsheet.getRange('B2:B')
  
  let email = nome+ '.'+ sobrenome + '@dominio.com.br';
  
  spreadsheet.getCurrentCell().setValue(email)
}
'''

**Comment by anapaulamafr** [comment]
Não consegui resolver o problema do loop, então a função só pega o último sobrenome para concatenar com todos os nomes. Não fiz a função da senha porque queria terminar a do e-mail.

function criarEmail() {
  let spreadsheet = SpreadsheetApp.getActive()
  let range1 = spreadsheet.getRange('A2:A5')
  let nomes = range1.getValues()
  let range2 = spreadsheet.getRange('B2:B5')
  let sobrenomes = range2.getValues()
  
  let dominio = '@dominio.com'
  
  let cont = 1
  let email = 's'
  let sobrenomeS = 'l'
  
  for (let nome of nomes) {
    for (let sobrenome of sobrenomes) {
      sobrenomeS = sobrenome
    }
    email = nome + '.' + sobrenomeS + dominio
    cont++
    spreadsheet.getRange('C' + cont).setValue(email.toLowerCase())
  }
}

**Comment by leofaria98** [comment]
Segue a tentativa do código 

`function gerarEmail() {
  let spreadsheet = SpreadsheetApp.getActive()
  let nomes =  spreadsheet.getRange('A2:A')
  let sobrenomes = spreadsheet.getRange('B2:B')
  let nome = nomes.getValue()
  let sobrenome = sobrenomes.getValue()
  let gera_email = nome + '.' + sobrenome + '@dominio.com'
  return gera_email;
}

function returnRand() {
   let spreadsheet = SpreadsheetApp.getActive()
   let range = spreadsheet.getRange('D2:D')
   let valores = range.getValues()
   let randomization = Math.random().toString();
   let lengthNumbers = randomization.length;
   let sort = randomization.substring(lengthNumbers, lengthNumbers - 1);
   return sort;
}
function gerarSenha() {
  let spreadsheet = SpreadsheetApp.getActive()
  let range = spreadsheet.getRange('D2:D')
  let retorno = range.getValues();
  let letras = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k' , 'l'];
  retorno = letras[returnRand()].toUpperCase() + letras[returnRand()] + letras[returnRand()] +
    returnRand() + returnRand() + returnRand();
  return retorno;
}
`

**Comment by c1275181** [comment]
(não consegui escrever nas celulas)

```
function getDados(){
var ss = SpreadsheetApp.getActiveSpreadsheet();
var sheet = ss.getSheets()[0];
var range = sheet.getRange(2,1,3,2);
var values = range.getValues();
  let contador =1
  let nome
  let sobreNome
  let senha = Math.random().toString(36).slice(2)
for (let row of values) {
    nome = row[0]
    sobreNome =  row[1]
}

**Comment by leofaria98** [comment]
Segue a tentativa do código 


```
function gerarEmail() {
  let spreadsheet = SpreadsheetApp.getActive()
  let nomes =  spreadsheet.getRange('A2:A')
  let sobrenomes = spreadsheet.getRange('B2:B')
  let nome = nomes.getValue()
  let sobrenome = sobrenomes.getValue()
  let gera_email = nome + '.' + sobrenome + '@dominio.com'
  return gera_email;
}

function returnRand() {
   let spreadsheet = SpreadsheetApp.getActive()
   let range = spreadsheet.getRange('D2:D')
   let valores = range.getValues()
   let randomization = Math.random().toString();
   let lengthNumbers = randomization.length;
   let sort = randomization.substring(lengthNumbers, lengthNumbers - 1);
   return sort;
}
function gerarSenha() {
  let spreadsheet = SpreadsheetApp.getActive()
  let range = spreadsheet.getRange('D2:D')
  let retorno = range.getValues();
  let letras = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k' , 'l'];
  retorno = letras[returnRand()].toUpperCase() + letras[returnRand()] + letras[returnRand()] +
    returnRand() + returnRand() + returnRand();
  return retorno;
}
```

**Comment by leofaria98** [comment]
Segue a tentativa do código

```javascript
function gerarEmail() {
  let spreadsheet = SpreadsheetApp.getActive()
  let nomes =  spreadsheet.getRange('A2:A')
  let sobrenomes = spreadsheet.getRange('B2:B')
  let nome = nomes.getValue()
  let sobrenome = sobrenomes.getValue()
  let gera_email = nome + '.' + sobrenome + '@dominio.com'
  return gera_email;
}

function returnRand() {
   let spreadsheet = SpreadsheetApp.getActive()
   let range = spreadsheet.getRange('D2:D')
   let valores = range.getValues()
   let randomization = Math.random().toString();
   let lengthNumbers = randomization.length;
   let sort = randomization.substring(lengthNumbers, lengthNumbers - 1);
   return sort;
}
function gerarSenha() {
  let spreadsheet = SpreadsheetApp.getActive()
  let range = spreadsheet.getRange('D2:D')
  let retorno = range.getValues();
  let letras = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k' , 'l'];
  retorno = letras[returnRand()].toUpperCase() + letras[returnRand()] + letras[returnRand()] +
    returnRand() + returnRand() + returnRand();
  return retorno;
}
```

**Comment by joselsantospqt** [comment]
function criarConta() {
  let count = 1;
  let spreadsheet = SpreadsheetApp.getActive()
  let nome = spreadsheet.getRange('A2:A').getValues()
  
    for(let linha of nome) {
    count++
    Logger.info('linha '+ linha)
    nome = spreadsheet.getRange('A' + count).getValues()
    if(!linha[0]){
      break 
    }
    
    let pular = spreadsheet.getRange('D' + count).getValues()[0][0]
    if(pular){
      Logger.info('pulou '+ count)
      continue 
    }
    
    for(let celula of linha) {
  
      let sobrenome = spreadsheet.getRange('B' + count).getValues()
 
      let email = spreadsheet.getRange('C' + count).setValue(nome + '.' +  sobrenome + '@gmail.com')
 
      let senha = spreadsheet.getRange('D'+ count).setValue(generateRandomNumber())
    }
 
}
}


function generateRandomNumber(){
        return Math.random();  
}

**Comment by joselsantospqt** [comment]
function criarConta() {
  let count = 1;
  let spreadsheet = SpreadsheetApp.getActive()
  let nome = spreadsheet.getRange('A2:A').getValues()
  
    for(let linha of nome) {
    count++
    Logger.info('linha '+ linha)
    nome = spreadsheet.getRange('A' + count).getValues()
    if(!linha[0]){
      break 
    }
    
    let pular = spreadsheet.getRange('D' + count).getValues()[0][0]
    if(pular){
      Logger.info('pulou '+ count)
      continue 
    }
    
    for(let celula of linha) {
  
      let sobrenome = spreadsheet.getRange('B' + count).getValues()
 
      let email = spreadsheet.getRange('C' + count).setValue(nome + '.' +  sobrenome + '@gmail.com')
 
      let senha = spreadsheet.getRange('D'+ count).setValue(generateRandomNumber())
    }
 
}
}


function generateRandomNumber(){
        return Math.random();  
}

**Comment by raul224** [comment]
```javascript
function geraEmail() {
  let spreadsheet = SpreadsheetApp.getActive()
  let range = spreadsheet.getRange('A2:B')
  let nomes = range.getValues()
  
  let count = 1
    
  for (let linha of nomes) {
    count++
    if (!linha[0]) {
      break
    }
    
    let nome = linha[0]
    let sobreNome = linha[1]
    
    let email = nome.toLowerCase() + '.' + sobreNome.toLowerCase() + '@dominio.com.br'
    spreadsheet.getRange('C' + count).setValue(email)
  }
}
```
