### ISSUE TITLE
Exercício 2 - Todo list 

### ISSUE THREAD

**Issue by ebertti** [ebertti/Javascript202#4]

**Comment by c1275181** [comment]
``` javascript
    document.addEventListener("keyup", event => {
        if (event.key === 'Enter') {
            let $nome = document.querySelector('.js_nome')
            let nome = $nome.value.trim()
            addItemLista(nome)
        }
    })
```

**Comment by fjuncal** [comment]
´´
  $adicionar.addEventListener('keypress', (e => {
        if (e.which === 13){
            let $nome = document.querySelector('.js_nome')
            let nome = $nome.value
            adicionarItemNaLista(nome)
        }
    }))
´´

**Comment by LizaroThedarark** [comment]
$nome.addEventListener('keyup', function (event) {
            let nome = $nome.value.trim();
            if(event.key === "Enter"){
                if(nome.length===0){
                    alert("campo vazio!");
                } else {
                    let $lista = document.querySelector(".js_lista");
                    let $li = document.createElement("li");
                    $li.innerText = nome;
                    $lista.append($li);
                }
            }
        });

**Comment by joselsantospqt** [comment]
function adicionarItemNaLista(nome) {
        document.addEventListener("keyup", event => {
            if (event.keyCode === 13) {
                let $lista = document.querySelector('.js_lista')
                let $li = document.createElement('li')
                $li.innerText = nome
                $lista.append($li)
            }
        });

**Comment by joselsantospqt** [comment]
` function adicionarItemNaLista(nome) {
        document.addEventListener("keyup", event => {
            if (event.keyCode === 13) {
                let $lista = document.querySelector('.js_lista')
                let $li = document.createElement('li')
                $li.innerText = nome
                $lista.append($li)
            }
        });
`

**Comment by joselsantospqt** [comment]
function adicionarItemNaLista(nome) {
        document.addEventListener("keyup", event => {
            if (event.keyCode === 13) {
                let $lista = document.querySelector('.js_lista')
                let $li = document.createElement('li')
                $li.innerText = nome
                $lista.append($li)
            }
        });

**Comment by anapaulamafr** [comment]
``` javascript

$nome.addEventListener('keyup', function(event) {
        let $nome = document.querySelector('.js_nome')
        let nome = $nome.value.trim()
        if (event.keyCode === 13) {
            adicionarItemNaLista(nome);
            $nome.value = ""
        }
    })

```

**Comment by Gabriel-Vianna** [comment]
```javascript

let $input = document.querySelector('.js_nome')
  $input.addEventListener('keyup', (e) => {
    if(e.key === 'Enter') {
        addItemEnter()
    }
  })

  function addItemEnter() {
    let $nome = document.querySelector('.js_nome')
        let nome = $nome.value
    
        if(nome) {
            let $lista = document.querySelector('.js_lista')
            let $li = document.createElement('li')
            $li.innerText = nome
            $lista.append($li)
        }
  } 

```

**Comment by rafaelrrs** [comment]
```javascript
$(document).keypress(function(e) {
    if(e.which == 13){
	let nome = $nome.value
        adicionarItemNaLista(nome)
    }
})
```

**Comment by raul224** [comment]
```javascript 
$nome.addEventListener("keydown", (event) => {
            if(event.key === 'Enter'){
                adicionarItemNaLista(nome)
            }
        })
```

**Comment by c1275181** [comment]
```javascript
    function addItemLista(nome) {
        if (nome) {
            let $lista = document.querySelector('.lista')
            let $li = document.createElement('li')
            $li.innerText = nome
            $lista.append($li)
            $li.addEventListener('click', () => {
                if ($li.getAttribute('style') === null) {
                    $li.style.textDecoration = "line-through"
                    $lista.append($li)
                } else {
                    $li.removeAttribute('style')
                }
            })
            $li.addEventListener('dblclick', () => {
                $li.remove()
            })
        }
    }







```
